In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

In [2]:
train_data = pd.read_csv(r"C:\Users\sidhu\OneDrive\Desktop\Kaggle\Titanic - Machine Learning from Disaster\data\train.csv")
train_data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [3]:
test_data = pd.read_csv(r"C:\Users\sidhu\OneDrive\Desktop\Kaggle\Titanic - Machine Learning from Disaster\data\train.csv")
test_data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [4]:
surviving_women = train_data.loc[train_data.Sex == "female"]["Survived"]
percent_of_women_alive = sum(surviving_women)/len(surviving_women) * 100

print("% of women who survived : ",percent_of_women_alive)

% of women who survived :  74.20382165605095

In [5]:
surviving_men = train_data.loc[train_data.Sex == "male"]["Survived"]
percent_of_men_alive = sum(surviving_men)/len(surviving_men) * 100

print("% of men who survived : ", percent_of_men_alive)

% of men who survived :  18.890814558058924

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
import optuna

y = train_data["Survived"]

features = ["Parch", "SibSp", "Sex", "Pclass"]

X = pd.get_dummies(train_data[features])
X_test = pd.get_dummies(test_data[features])

X_test = X_test.reindex(columns=X.columns, fill_value=0)

X_train, X_val, y_train, y_val = train_test_split(
    X,
    y,
    test_size=0.2,
    stratify=y,
    random_state=1
)


def model_evaluation(trial):

    model = RandomForestClassifier(
        n_estimators=trial.suggest_int("n_estimators", 50, 500),
        max_depth=trial.suggest_int("max_depth", 2, 30),
        min_samples_split=trial.suggest_int("min_samples_split", 2, 20),
        min_samples_leaf=trial.suggest_int("min_samples_leaf", 1, 10),
        max_features=trial.suggest_categorical(
            "max_features",
            ["sqrt", "log2", None]
        ),
        random_state=1
    )

    model.fit(X_train, y_train)

    val_predictions = model.predict(X_val)

    val_accuracy = accuracy_score(y_val, val_predictions)

    return val_accuracy


study = optuna.create_study(direction="maximize")

study.optimize(model_evaluation, n_trials=100)

print("Best parameters:\n", study.best_params)

print("\nBest validation accuracy percentage:\n", study.best_value * 100, "%")

[I 2026-08-12 00:31:34,602] A new study created in memory with name: no-name-807a0065-2906-4677-9f15-158a0502e650
[I 2026-08-12 00:31:35,587] Trial 0 finished with value: 0.8268156424581006 and parameters: {'n_estimators': 382, 'max_depth': 14, 'min_samples_split': 15, 'min_samples_leaf': 5, 'max_features': 'sqrt'}. Best is trial 0 with value: 0.8268156424581006.
[I 2026-08-12 00:31:36,065] Trial 1 finished with value: 0.8100558659217877 and parameters: {'n_estimators': 183, 'max_depth': 28, 'min_samples_split': 7, 'min_samples_leaf': 6, 'max_features': None}. Best is trial 0 with value: 0.8268156424581006.
[I 2026-08-12 00:31:36,996] Trial 2 finished with value: 0.8156424581005587 and parameters: {'n_estimators': 353, 'max_depth': 30, 'min_samples_split': 20, 'min_samples_leaf': 3, 'max_features': 'sqrt'}. Best is trial 0 with value: 0.8268156424581006.
[I 2026-08-12 00:31:37,335] Trial 3 finished with value: 0.8044692737430168 and parameters: {'n_estimators': 144, 'max_depth': 15, 'min_samples_split': 15, 'min_samples_leaf': 2, 'max_features': 'log2'}. Best is trial 0 with value: 0.8268156424581006.
[I 2026-08-12 00:31:37,800] Trial 4 finished with value: 0.8100558659217877 and parameters: {'n_estimators': 209, 'max_depth': 23, 'min_samples_split': 14, 'min_samples_leaf': 4, 'max_features': 'log2'}. Best is trial 0 with value: 0.8268156424581006.
[I 2026-08-12 00:31:38,567] Trial 5 finished with value: 0.8044692737430168 and parameters: {'n_estimators': 347, 'max_depth': 25, 'min_samples_split': 14, 'min_samples_leaf': 3, 'max_features': None}. Best is trial 0 with value: 0.8268156424581006.
[I 2026-08-12 00:31:39,315] Trial 6 finished with value: 0.8156424581005587 and parameters: {'n_estimators': 339, 'max_depth': 17, 'min_samples_split': 20, 'min_samples_leaf': 3, 'max_features': 'sqrt'}. Best is trial 0 with value: 0.8268156424581006.
[I 2026-08-12 00:31:40,155] Trial 7 finished with value: 0.8212290502793296 and parameters: {'n_estimators': 400, 'max_depth': 29, 'min_samples_split': 5, 'min_samples_leaf': 6, 'max_features': 'sqrt'}. Best is trial 0 with value: 0.8268156424581006.
[I 2026-08-12 00:31:40,286] Trial 8 finished with value: 0.8044692737430168 and parameters: {'n_estimators': 50, 'max_depth': 13, 'min_samples_split': 16, 'min_samples_leaf': 5, 'max_features': None}. Best is trial 0 with value: 0.8268156424581006.
[I 2026-08-12 00:31:41,066] Trial 9 finished with value: 0.7988826815642458 and parameters: {'n_estimators': 359, 'max_depth': 24, 'min_samples_split': 9, 'min_samples_leaf': 3, 'max_features': 'log2'}. Best is trial 0 with value: 0.8268156424581006.
[I 2026-08-12 00:31:42,064] Trial 10 finished with value: 0.8156424581005587 and parameters: {'n_estimators': 497, 'max_depth': 2, 'min_samples_split': 3, 'min_samples_leaf': 10, 'max_features': 'sqrt'}. Best is trial 0 with value: 0.8268156424581006.
[I 2026-08-12 00:31:43,042] Trial 11 finished with value: 0.8324022346368715 and parameters: {'n_estimators': 464, 'max_depth': 7, 'min_samples_split': 2, 'min_samples_leaf': 7, 'max_features': 'sqrt'}. Best is trial 11 with value: 0.8324022346368715.
[I 2026-08-12 00:31:44,145] Trial 12 finished with value: 0.8268156424581006 and parameters: {'n_estimators': 492, 'max_depth': 7, 'min_samples_split': 10, 'min_samples_leaf': 8, 'max_features': 'sqrt'}. Best is trial 11 with value: 0.8324022346368715.
[I 2026-08-12 00:31:45,034] Trial 13 finished with value: 0.8268156424581006 and parameters: {'n_estimators': 273, 'max_depth': 9, 'min_samples_split': 2, 'min_samples_leaf': 8, 'max_features': 'sqrt'}. Best is trial 11 with value: 0.8324022346368715.
[I 2026-08-12 00:31:45,925] Trial 14 finished with value: 0.8268156424581006 and parameters: {'n_estimators': 422, 'max_depth': 8, 'min_samples_split': 10, 'min_samples_leaf': 8, 'max_features': 'sqrt'}. Best is trial 11 with value: 0.8324022346368715.
[I 2026-08-12 00:31:46,929] Trial 15 finished with value: 0.8156424581005587 and parameters: {'n_estimators': 436, 'max_depth': 2, 'min_samples_split': 17, 'min_samples_leaf': 6, 'max_features': 'sqrt'}. Best is trial 11 with value: 0.8324022346368715.
[I 2026-08-12 00:31:47,597] Trial 16 finished with value: 0.7988826815642458 and parameters: {'n_estimators': 298, 'max_depth': 19, 'min_samples_split': 6, 'min_samples_leaf': 1, 'max_features': 'sqrt'}. Best is trial 11 with value: 0.8324022346368715.
[I 2026-08-12 00:31:48,661] Trial 17 finished with value: 0.8324022346368715 and parameters: {'n_estimators': 455, 'max_depth': 11, 'min_samples_split': 12, 'min_samples_leaf': 10, 'max_features': 'sqrt'}. Best is trial 11 with value: 0.8324022346368715.
[I 2026-08-12 00:31:49,715] Trial 18 finished with value: 0.8324022346368715 and parameters: {'n_estimators': 455, 'max_depth': 10, 'min_samples_split': 12, 'min_samples_leaf': 10, 'max_features': 'log2'}. Best is trial 11 with value: 0.8324022346368715.
[I 2026-08-12 00:31:50,651] Trial 19 finished with value: 0.8100558659217877 and parameters: {'n_estimators': 459, 'max_depth': 6, 'min_samples_split': 4, 'min_samples_leaf': 9, 'max_features': None}. Best is trial 11 with value: 0.8324022346368715.
[I 2026-08-12 00:31:51,363] Trial 20 finished with value: 0.8324022346368715 and parameters: {'n_estimators': 296, 'max_depth': 11, 'min_samples_split': 8, 'min_samples_leaf': 7, 'max_features': 'sqrt'}. Best is trial 11 with value: 0.8324022346368715.
[I 2026-08-12 00:31:52,341] Trial 21 finished with value: 0.8268156424581006 and parameters: {'n_estimators': 459, 'max_depth': 5, 'min_samples_split': 12, 'min_samples_leaf': 10, 'max_features': 'log2'}. Best is trial 11 with value: 0.8324022346368715.
[I 2026-08-12 00:31:53,299] Trial 22 finished with value: 0.8324022346368715 and parameters: {'n_estimators': 460, 'max_depth': 11, 'min_samples_split': 12, 'min_samples_leaf': 9, 'max_features': 'log2'}. Best is trial 11 with value: 0.8324022346368715.
[I 2026-08-12 00:31:54,164] Trial 23 finished with value: 0.8324022346368715 and parameters: {'n_estimators': 415, 'max_depth': 11, 'min_samples_split': 12, 'min_samples_leaf': 10, 'max_features': 'log2'}. Best is trial 11 with value: 0.8324022346368715.
[I 2026-08-12 00:31:55,486] Trial 24 finished with value: 0.8268156424581006 and parameters: {'n_estimators': 499, 'max_depth': 4, 'min_samples_split': 11, 'min_samples_leaf': 9, 'max_features': 'log2'}. Best is trial 11 with value: 0.8324022346368715.
[I 2026-08-12 00:31:56,477] Trial 25 finished with value: 0.8324022346368715 and parameters: {'n_estimators': 445, 'max_depth': 9, 'min_samples_split': 18, 'min_samples_leaf': 7, 'max_features': 'log2'}. Best is trial 11 with value: 0.8324022346368715.
[I 2026-08-12 00:31:57,324] Trial 26 finished with value: 0.8324022346368715 and parameters: {'n_estimators': 401, 'max_depth': 18, 'min_samples_split': 7, 'min_samples_leaf': 9, 'max_features': 'sqrt'}. Best is trial 11 with value: 0.8324022346368715.
[I 2026-08-12 00:31:58,626] Trial 27 finished with value: 0.8324022346368715 and parameters: {'n_estimators': 471, 'max_depth': 12, 'min_samples_split': 13, 'min_samples_leaf': 10, 'max_features': 'sqrt'}. Best is trial 11 with value: 0.8324022346368715.
[I 2026-08-12 00:31:59,527] Trial 28 finished with value: 0.8100558659217877 and parameters: {'n_estimators': 382, 'max_depth': 16, 'min_samples_split': 9, 'min_samples_leaf': 8, 'max_features': None}. Best is trial 11 with value: 0.8324022346368715.
[I 2026-08-12 00:32:00,303] Trial 29 finished with value: 0.8324022346368715 and parameters: {'n_estimators': 385, 'max_depth': 14, 'min_samples_split': 18, 'min_samples_leaf': 7, 'max_features': 'log2'}. Best is trial 11 with value: 0.8324022346368715.
[I 2026-08-12 00:32:01,166] Trial 30 finished with value: 0.8324022346368715 and parameters: {'n_estimators': 433, 'max_depth': 20, 'min_samples_split': 2, 'min_samples_leaf': 9, 'max_features': 'sqrt'}. Best is trial 11 with value: 0.8324022346368715.
[I 2026-08-12 00:32:01,813] Trial 31 finished with value: 0.8324022346368715 and parameters: {'n_estimators': 279, 'max_depth': 10, 'min_samples_split': 8, 'min_samples_leaf': 7, 'max_features': 'sqrt'}. Best is trial 11 with value: 0.8324022346368715.
[I 2026-08-12 00:32:02,006] Trial 32 finished with value: 0.7988826815642458 and parameters: {'n_estimators': 85, 'max_depth': 13, 'min_samples_split': 5, 'min_samples_leaf': 5, 'max_features': 'sqrt'}. Best is trial 11 with value: 0.8324022346368715.
[I 2026-08-12 00:32:02,477] Trial 33 finished with value: 0.8212290502793296 and parameters: {'n_estimators': 231, 'max_depth': 8, 'min_samples_split': 7, 'min_samples_leaf': 6, 'max_features': 'sqrt'}. Best is trial 11 with value: 0.8324022346368715.
[I 2026-08-12 00:32:03,092] Trial 34 finished with value: 0.8268156424581006 and parameters: {'n_estimators': 315, 'max_depth': 4, 'min_samples_split': 10, 'min_samples_leaf': 7, 'max_features': 'sqrt'}. Best is trial 11 with value: 0.8324022346368715.
[I 2026-08-12 00:32:03,700] Trial 35 finished with value: 0.8268156424581006 and parameters: {'n_estimators': 258, 'max_depth': 11, 'min_samples_split': 13, 'min_samples_leaf': 8, 'max_features': 'sqrt'}. Best is trial 11 with value: 0.8324022346368715.
[I 2026-08-12 00:32:04,178] Trial 36 finished with value: 0.8044692737430168 and parameters: {'n_estimators': 172, 'max_depth': 14, 'min_samples_split': 15, 'min_samples_leaf': 5, 'max_features': None}. Best is trial 11 with value: 0.8324022346368715.
[I 2026-08-12 00:32:05,032] Trial 37 finished with value: 0.8212290502793296 and parameters: {'n_estimators': 372, 'max_depth': 7, 'min_samples_split': 8, 'min_samples_leaf': 4, 'max_features': 'log2'}. Best is trial 11 with value: 0.8324022346368715.
[I 2026-08-12 00:32:05,354] Trial 38 finished with value: 0.8324022346368715 and parameters: {'n_estimators': 134, 'max_depth': 15, 'min_samples_split': 14, 'min_samples_leaf': 10, 'max_features': 'sqrt'}. Best is trial 11 with value: 0.8324022346368715.
[I 2026-08-12 00:32:06,582] Trial 39 finished with value: 0.8100558659217877 and parameters: {'n_estimators': 480, 'max_depth': 10, 'min_samples_split': 11, 'min_samples_leaf': 4, 'max_features': 'sqrt'}. Best is trial 11 with value: 0.8324022346368715.
[I 2026-08-12 00:32:07,246] Trial 40 finished with value: 0.8268156424581006 and parameters: {'n_estimators': 334, 'max_depth': 21, 'min_samples_split': 4, 'min_samples_leaf': 6, 'max_features': 'log2'}. Best is trial 11 with value: 0.8324022346368715.
[I 2026-08-12 00:32:08,163] Trial 41 finished with value: 0.8324022346368715 and parameters: {'n_estimators': 457, 'max_depth': 12, 'min_samples_split': 12, 'min_samples_leaf': 9, 'max_features': 'log2'}. Best is trial 11 with value: 0.8324022346368715.
[I 2026-08-12 00:32:08,984] Trial 42 finished with value: 0.8324022346368715 and parameters: {'n_estimators': 410, 'max_depth': 10, 'min_samples_split': 13, 'min_samples_leaf': 9, 'max_features': 'log2'}. Best is trial 11 with value: 0.8324022346368715.
[I 2026-08-12 00:32:09,963] Trial 43 finished with value: 0.8324022346368715 and parameters: {'n_estimators': 475, 'max_depth': 12, 'min_samples_split': 11, 'min_samples_leaf': 10, 'max_features': 'log2'}. Best is trial 11 with value: 0.8324022346368715.
[I 2026-08-12 00:32:10,991] Trial 44 finished with value: 0.8268156424581006 and parameters: {'n_estimators': 443, 'max_depth': 6, 'min_samples_split': 15, 'min_samples_leaf': 8, 'max_features': 'log2'}. Best is trial 11 with value: 0.8324022346368715.
[I 2026-08-12 00:32:11,460] Trial 45 finished with value: 0.8100558659217877 and parameters: {'n_estimators': 215, 'max_depth': 8, 'min_samples_split': 9, 'min_samples_leaf': 7, 'max_features': None}. Best is trial 11 with value: 0.8324022346368715.
[I 2026-08-12 00:32:13,206] Trial 46 finished with value: 0.8324022346368715 and parameters: {'n_estimators': 425, 'max_depth': 16, 'min_samples_split': 14, 'min_samples_leaf': 9, 'max_features': 'log2'}. Best is trial 11 with value: 0.8324022346368715.
[I 2026-08-12 00:32:14,103] Trial 47 finished with value: 0.8324022346368715 and parameters: {'n_estimators': 394, 'max_depth': 9, 'min_samples_split': 6, 'min_samples_leaf': 10, 'max_features': 'sqrt'}. Best is trial 11 with value: 0.8324022346368715.
[I 2026-08-12 00:32:14,959] Trial 48 finished with value: 0.8268156424581006 and parameters: {'n_estimators': 365, 'max_depth': 13, 'min_samples_split': 16, 'min_samples_leaf': 8, 'max_features': 'sqrt'}. Best is trial 11 with value: 0.8324022346368715.
[I 2026-08-12 00:32:15,843] Trial 49 finished with value: 0.8268156424581006 and parameters: {'n_estimators': 334, 'max_depth': 11, 'min_samples_split': 3, 'min_samples_leaf': 6, 'max_features': 'log2'}. Best is trial 11 with value: 0.8324022346368715.
[I 2026-08-12 00:32:17,544] Trial 50 finished with value: 0.8324022346368715 and parameters: {'n_estimators': 484, 'max_depth': 7, 'min_samples_split': 8, 'min_samples_leaf': 9, 'max_features': 'sqrt'}. Best is trial 11 with value: 0.8324022346368715.
[I 2026-08-12 00:32:18,600] Trial 51 finished with value: 0.8324022346368715 and parameters: {'n_estimators': 424, 'max_depth': 27, 'min_samples_split': 12, 'min_samples_leaf': 10, 'max_features': 'log2'}. Best is trial 11 with value: 0.8324022346368715.
[I 2026-08-12 00:32:19,573] Trial 52 finished with value: 0.8324022346368715 and parameters: {'n_estimators': 462, 'max_depth': 11, 'min_samples_split': 10, 'min_samples_leaf': 10, 'max_features': 'log2'}. Best is trial 11 with value: 0.8324022346368715.
[I 2026-08-12 00:32:20,426] Trial 53 finished with value: 0.8324022346368715 and parameters: {'n_estimators': 416, 'max_depth': 9, 'min_samples_split': 12, 'min_samples_leaf': 10, 'max_features': 'log2'}. Best is trial 11 with value: 0.8324022346368715.
[I 2026-08-12 00:32:21,389] Trial 54 finished with value: 0.8324022346368715 and parameters: {'n_estimators': 444, 'max_depth': 14, 'min_samples_split': 11, 'min_samples_leaf': 9, 'max_features': 'log2'}. Best is trial 11 with value: 0.8324022346368715.
[I 2026-08-12 00:32:22,866] Trial 55 finished with value: 0.8268156424581006 and parameters: {'n_estimators': 487, 'max_depth': 5, 'min_samples_split': 13, 'min_samples_leaf': 10, 'max_features': 'log2'}. Best is trial 11 with value: 0.8324022346368715.
[I 2026-08-12 00:32:23,996] Trial 56 finished with value: 0.8100558659217877 and parameters: {'n_estimators': 498, 'max_depth': 11, 'min_samples_split': 12, 'min_samples_leaf': 8, 'max_features': None}. Best is trial 11 with value: 0.8324022346368715.
[I 2026-08-12 00:32:25,037] Trial 57 finished with value: 0.8324022346368715 and parameters: {'n_estimators': 405, 'max_depth': 8, 'min_samples_split': 16, 'min_samples_leaf': 9, 'max_features': 'sqrt'}. Best is trial 11 with value: 0.8324022346368715.
[I 2026-08-12 00:32:26,156] Trial 58 finished with value: 0.8324022346368715 and parameters: {'n_estimators': 456, 'max_depth': 12, 'min_samples_split': 9, 'min_samples_leaf': 10, 'max_features': 'log2'}. Best is trial 11 with value: 0.8324022346368715.
[I 2026-08-12 00:32:27,138] Trial 59 finished with value: 0.8212290502793296 and parameters: {'n_estimators': 470, 'max_depth': 3, 'min_samples_split': 14, 'min_samples_leaf': 1, 'max_features': 'sqrt'}. Best is trial 11 with value: 0.8324022346368715.
[I 2026-08-12 00:32:28,177] Trial 60 finished with value: 0.8324022346368715 and parameters: {'n_estimators': 433, 'max_depth': 6, 'min_samples_split': 11, 'min_samples_leaf': 7, 'max_features': 'log2'}. Best is trial 11 with value: 0.8324022346368715.
[I 2026-08-12 00:32:29,255] Trial 61 finished with value: 0.8324022346368715 and parameters: {'n_estimators': 444, 'max_depth': 9, 'min_samples_split': 18, 'min_samples_leaf': 7, 'max_features': 'log2'}. Best is trial 11 with value: 0.8324022346368715.
[I 2026-08-12 00:32:30,206] Trial 62 finished with value: 0.8324022346368715 and parameters: {'n_estimators': 450, 'max_depth': 10, 'min_samples_split': 19, 'min_samples_leaf': 7, 'max_features': 'log2'}. Best is trial 11 with value: 0.8324022346368715.
[I 2026-08-12 00:32:31,003] Trial 63 finished with value: 0.8324022346368715 and parameters: {'n_estimators': 391, 'max_depth': 7, 'min_samples_split': 20, 'min_samples_leaf': 6, 'max_features': 'log2'}. Best is trial 11 with value: 0.8324022346368715.
[I 2026-08-12 00:32:32,147] Trial 64 finished with value: 0.8268156424581006 and parameters: {'n_estimators': 469, 'max_depth': 13, 'min_samples_split': 5, 'min_samples_leaf': 8, 'max_features': 'sqrt'}. Best is trial 11 with value: 0.8324022346368715.
[I 2026-08-12 00:32:32,876] Trial 65 finished with value: 0.8324022346368715 and parameters: {'n_estimators': 349, 'max_depth': 10, 'min_samples_split': 17, 'min_samples_leaf': 9, 'max_features': 'log2'}. Best is trial 11 with value: 0.8324022346368715.
[I 2026-08-12 00:32:33,739] Trial 66 finished with value: 0.8268156424581006 and parameters: {'n_estimators': 411, 'max_depth': 9, 'min_samples_split': 6, 'min_samples_leaf': 6, 'max_features': 'sqrt'}. Best is trial 11 with value: 0.8324022346368715.
[I 2026-08-12 00:32:34,662] Trial 67 finished with value: 0.7988826815642458 and parameters: {'n_estimators': 429, 'max_depth': 15, 'min_samples_split': 7, 'min_samples_leaf': 2, 'max_features': None}. Best is trial 11 with value: 0.8324022346368715.
[I 2026-08-12 00:32:35,317] Trial 68 finished with value: 0.8324022346368715 and parameters: {'n_estimators': 318, 'max_depth': 11, 'min_samples_split': 10, 'min_samples_leaf': 10, 'max_features': 'log2'}. Best is trial 11 with value: 0.8324022346368715.
[I 2026-08-12 00:32:36,164] Trial 69 finished with value: 0.8324022346368715 and parameters: {'n_estimators': 372, 'max_depth': 8, 'min_samples_split': 13, 'min_samples_leaf': 7, 'max_features': 'sqrt'}. Best is trial 11 with value: 0.8324022346368715.
[I 2026-08-12 00:32:37,396] Trial 70 finished with value: 0.8268156424581006 and parameters: {'n_estimators': 485, 'max_depth': 5, 'min_samples_split': 3, 'min_samples_leaf': 5, 'max_features': 'log2'}. Best is trial 11 with value: 0.8324022346368715.
[I 2026-08-12 00:32:38,270] Trial 71 finished with value: 0.8268156424581006 and parameters: {'n_estimators': 399, 'max_depth': 21, 'min_samples_split': 7, 'min_samples_leaf': 8, 'max_features': 'sqrt'}. Best is trial 11 with value: 0.8324022346368715.
[I 2026-08-12 00:32:39,199] Trial 72 finished with value: 0.8324022346368715 and parameters: {'n_estimators': 445, 'max_depth': 17, 'min_samples_split': 4, 'min_samples_leaf': 9, 'max_features': 'sqrt'}. Best is trial 11 with value: 0.8324022346368715.
[I 2026-08-12 00:32:39,712] Trial 73 finished with value: 0.8324022346368715 and parameters: {'n_estimators': 242, 'max_depth': 23, 'min_samples_split': 15, 'min_samples_leaf': 9, 'max_features': 'sqrt'}. Best is trial 11 with value: 0.8324022346368715.
[I 2026-08-12 00:32:40,663] Trial 74 finished with value: 0.8324022346368715 and parameters: {'n_estimators': 464, 'max_depth': 18, 'min_samples_split': 9, 'min_samples_leaf': 10, 'max_features': 'sqrt'}. Best is trial 11 with value: 0.8324022346368715.
[I 2026-08-12 00:32:41,247] Trial 75 finished with value: 0.8268156424581006 and parameters: {'n_estimators': 286, 'max_depth': 12, 'min_samples_split': 2, 'min_samples_leaf': 8, 'max_features': 'sqrt'}. Best is trial 11 with value: 0.8324022346368715.
[I 2026-08-12 00:32:42,101] Trial 76 finished with value: 0.8324022346368715 and parameters: {'n_estimators': 419, 'max_depth': 30, 'min_samples_split': 5, 'min_samples_leaf': 10, 'max_features': 'sqrt'}. Best is trial 11 with value: 0.8324022346368715.
[I 2026-08-12 00:32:42,991] Trial 77 finished with value: 0.8324022346368715 and parameters: {'n_estimators': 435, 'max_depth': 14, 'min_samples_split': 8, 'min_samples_leaf': 9, 'max_features': 'log2'}. Best is trial 11 with value: 0.8324022346368715.

Best parameters:
 {'n_estimators': 464, 'max_depth': 7, 'min_samples_split': 2, 'min_samples_leaf': 7, 'max_features': 'sqrt'}

Best validation accuracy percentage:
 83.24022346368714 %

I made use of Optuna (hyperparamter optimization framework that makes use of Bayesian style of optimization) to intelligently select ideal set of hyperparamter values after manually giving either a set of values to choose from or a range of values, within which to choose from, for each hyper parameter.

 Something i missed earlier which is a crucial step to maximise accuracy, is understanding the inter-relationships within the feature set via EDA and doing feature engineering to select the best set of features. This will be covered in the next version.