In [11]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

In [12]:
train_data = pd.read_csv(r"C:\Users\sidhu\OneDrive\Desktop\Kaggle\Titanic - Machine Learning from Disaster\data\train.csv")
train_data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [13]:
test_data = pd.read_csv(r"C:\Users\sidhu\OneDrive\Desktop\Kaggle\Titanic - Machine Learning from Disaster\data\test.csv")
test_data.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [14]:
surviving_women = train_data.loc[train_data.Sex == "female"]["Survived"]
percent_of_women_alive = sum(surviving_women)/len(surviving_women) * 100

print("% of women who survived : ",percent_of_women_alive)

% of women who survived :  74.20382165605095

In [15]:
surviving_men = train_data.loc[train_data.Sex == "male"]["Survived"]
percent_of_men_alive = sum(surviving_men)/len(surviving_men) * 100

print("% of men who survived : ", percent_of_men_alive)

% of men who survived :  18.890814558058924

In [16]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
import optuna

y = train_data["Survived"]

features = ["Parch", "SibSp", "Sex", "Pclass"]

X = pd.get_dummies(train_data[features])
X_test = pd.get_dummies(test_data[features])

X_test = X_test.reindex(columns=X.columns, fill_value=0)

X_train, X_val, y_train, y_val = train_test_split(
    X,
    y,
    test_size=0.2,
    stratify=y,
    random_state=1
)


def model_evaluation(trial):

    model = RandomForestClassifier(
        n_estimators=trial.suggest_int("n_estimators", 50, 500),
        max_depth=trial.suggest_int("max_depth", 2, 30),
        min_samples_split=trial.suggest_int("min_samples_split", 2, 20),
        min_samples_leaf=trial.suggest_int("min_samples_leaf", 1, 10),
        max_features=trial.suggest_categorical(
            "max_features",
            ["sqrt", "log2", None]
        ),
        random_state=1
    )

    model.fit(X_train, y_train)

    val_predictions = model.predict(X_val)

    val_accuracy = accuracy_score(y_val, val_predictions)

    return val_accuracy


study = optuna.create_study(direction="maximize")

study.optimize(model_evaluation, n_trials=100)

print("Best parameters:\n", study.best_params)

print("\nBest validation accuracy percentage:\n", study.best_value * 100, "%")

[I 2026-09-01 01:05:37,788] A new study created in memory with name: no-name-7989408a-a66d-4f3d-a0d0-6016b7513459

[I 2026-09-01 01:05:39,366] Trial 0 finished with value: 0.8324022346368715 and parameters: {'n_estimators': 480, 'max_depth': 26, 'min_samples_split': 20, 'min_samples_leaf': 8, 'max_features': 'log2'}. Best is trial 0 with value: 0.8324022346368715.
[I 2026-09-01 01:05:39,527] Trial 1 finished with value: 0.8268156424581006 and parameters: {'n_estimators': 67, 'max_depth': 17, 'min_samples_split': 18, 'min_samples_leaf': 5, 'max_features': 'log2'}. Best is trial 0 with value: 0.8324022346368715.
[I 2026-09-01 01:05:40,673] Trial 2 finished with value: 0.8100558659217877 and parameters: {'n_estimators': 389, 'max_depth': 14, 'min_samples_split': 15, 'min_samples_leaf': 6, 'max_features': None}. Best is trial 0 with value: 0.8324022346368715.
[I 2026-09-01 01:05:41,983] Trial 3 finished with value: 0.8044692737430168 and parameters: {'n_estimators': 400, 'max_depth': 14, 'min_samples_split': 18, 'min_samples_leaf': 3, 'max_features': None}. Best is trial 0 with value: 0.8324022346368715.
[I 2026-09-01 01:05:42,409] Trial 4 finished with value: 0.7988826815642458 and parameters: {'n_estimators': 63, 'max_depth': 25, 'min_samples_split': 12, 'min_samples_leaf': 1, 'max_features': None}. Best is trial 0 with value: 0.8324022346368715.
[I 2026-09-01 01:05:43,137] Trial 5 finished with value: 0.8212290502793296 and parameters: {'n_estimators': 290, 'max_depth': 18, 'min_samples_split': 2, 'min_samples_leaf': 10, 'max_features': 'log2'}. Best is trial 0 with value: 0.8324022346368715.
[I 2026-09-01 01:05:44,232] Trial 6 finished with value: 0.8044692737430168 and parameters: {'n_estimators': 424, 'max_depth': 28, 'min_samples_split': 4, 'min_samples_leaf': 4, 'max_features': 'log2'}. Best is trial 0 with value: 0.8324022346368715.
[I 2026-09-01 01:05:44,937] Trial 7 finished with value: 0.8268156424581006 and parameters: {'n_estimators': 314, 'max_depth': 25, 'min_samples_split': 17, 'min_samples_leaf': 5, 'max_features': 'log2'}. Best is trial 0 with value: 0.8324022346368715.
[I 2026-09-01 01:05:45,597] Trial 8 finished with value: 0.8212290502793296 and parameters: {'n_estimators': 306, 'max_depth': 3, 'min_samples_split': 7, 'min_samples_leaf': 2, 'max_features': 'log2'}. Best is trial 0 with value: 0.8324022346368715.
[I 2026-09-01 01:05:46,402] Trial 9 finished with value: 0.8156424581005587 and parameters: {'n_estimators': 364, 'max_depth': 7, 'min_samples_split': 17, 'min_samples_leaf': 1, 'max_features': 'sqrt'}. Best is trial 0 with value: 0.8324022346368715.
[I 2026-09-01 01:05:46,807] Trial 10 finished with value: 0.8324022346368715 and parameters: {'n_estimators': 179, 'max_depth': 30, 'min_samples_split': 10, 'min_samples_leaf': 10, 'max_features': 'sqrt'}. Best is trial 0 with value: 0.8324022346368715.
[I 2026-09-01 01:05:47,259] Trial 11 finished with value: 0.8324022346368715 and parameters: {'n_estimators': 188, 'max_depth': 30, 'min_samples_split': 10, 'min_samples_leaf': 10, 'max_features': 'sqrt'}. Best is trial 0 with value: 0.8324022346368715.
[I 2026-09-01 01:05:48,375] Trial 12 finished with value: 0.8268156424581006 and parameters: {'n_estimators': 497, 'max_depth': 24, 'min_samples_split': 12, 'min_samples_leaf': 8, 'max_features': 'sqrt'}. Best is trial 0 with value: 0.8324022346368715.
[I 2026-09-01 01:05:48,829] Trial 13 finished with value: 0.8324022346368715 and parameters: {'n_estimators': 183, 'max_depth': 21, 'min_samples_split': 7, 'min_samples_leaf': 8, 'max_features': 'sqrt'}. Best is trial 0 with value: 0.8324022346368715.
[I 2026-09-01 01:05:49,257] Trial 14 finished with value: 0.8324022346368715 and parameters: {'n_estimators': 191, 'max_depth': 30, 'min_samples_split': 20, 'min_samples_leaf': 8, 'max_features': 'sqrt'}. Best is trial 0 with value: 0.8324022346368715.
[I 2026-09-01 01:05:50,262] Trial 15 finished with value: 0.8324022346368715 and parameters: {'n_estimators': 493, 'max_depth': 22, 'min_samples_split': 14, 'min_samples_leaf': 9, 'max_features': 'log2'}. Best is trial 0 with value: 0.8324022346368715.
[I 2026-09-01 01:05:50,582] Trial 16 finished with value: 0.8324022346368715 and parameters: {'n_estimators': 131, 'max_depth': 27, 'min_samples_split': 8, 'min_samples_leaf': 7, 'max_features': 'sqrt'}. Best is trial 0 with value: 0.8324022346368715.
[I 2026-09-01 01:05:51,122] Trial 17 finished with value: 0.8324022346368715 and parameters: {'n_estimators': 249, 'max_depth': 20, 'min_samples_split': 20, 'min_samples_leaf': 9, 'max_features': 'sqrt'}. Best is trial 0 with value: 0.8324022346368715.
[I 2026-09-01 01:05:52,113] Trial 18 finished with value: 0.8324022346368715 and parameters: {'n_estimators': 445, 'max_depth': 27, 'min_samples_split': 5, 'min_samples_leaf': 7, 'max_features': 'log2'}. Best is trial 0 with value: 0.8324022346368715.
[I 2026-09-01 01:05:52,402] Trial 19 finished with value: 0.8268156424581006 and parameters: {'n_estimators': 118, 'max_depth': 30, 'min_samples_split': 10, 'min_samples_leaf': 10, 'max_features': None}. Best is trial 0 with value: 0.8324022346368715.
[I 2026-09-01 01:05:52,962] Trial 20 finished with value: 0.8324022346368715 and parameters: {'n_estimators': 252, 'max_depth': 24, 'min_samples_split': 14, 'min_samples_leaf': 9, 'max_features': 'sqrt'}. Best is trial 0 with value: 0.8324022346368715.
[I 2026-09-01 01:05:53,397] Trial 21 finished with value: 0.8324022346368715 and parameters: {'n_estimators': 189, 'max_depth': 30, 'min_samples_split': 11, 'min_samples_leaf': 10, 'max_features': 'sqrt'}. Best is trial 0 with value: 0.8324022346368715.
[I 2026-09-01 01:05:53,732] Trial 22 finished with value: 0.8324022346368715 and parameters: {'n_estimators': 138, 'max_depth': 27, 'min_samples_split': 9, 'min_samples_leaf': 10, 'max_features': 'sqrt'}. Best is trial 0 with value: 0.8324022346368715.
[I 2026-09-01 01:05:54,447] Trial 23 finished with value: 0.8324022346368715 and parameters: {'n_estimators': 227, 'max_depth': 28, 'min_samples_split': 13, 'min_samples_leaf': 9, 'max_features': 'sqrt'}. Best is trial 0 with value: 0.8324022346368715.
[I 2026-09-01 01:05:55,235] Trial 24 finished with value: 0.8324022346368715 and parameters: {'n_estimators': 356, 'max_depth': 23, 'min_samples_split': 5, 'min_samples_leaf': 7, 'max_features': 'sqrt'}. Best is trial 0 with value: 0.8324022346368715.
[I 2026-09-01 01:05:55,512] Trial 25 finished with value: 0.8324022346368715 and parameters: {'n_estimators': 106, 'max_depth': 26, 'min_samples_split': 10, 'min_samples_leaf': 8, 'max_features': 'log2'}. Best is trial 0 with value: 0.8324022346368715.
[I 2026-09-01 01:05:55,902] Trial 26 finished with value: 0.8324022346368715 and parameters: {'n_estimators': 169, 'max_depth': 30, 'min_samples_split': 15, 'min_samples_leaf': 9, 'max_features': 'sqrt'}. Best is trial 0 with value: 0.8324022346368715.
[I 2026-09-01 01:05:56,500] Trial 27 finished with value: 0.8324022346368715 and parameters: {'n_estimators': 228, 'max_depth': 28, 'min_samples_split': 2, 'min_samples_leaf': 10, 'max_features': 'sqrt'}. Best is trial 0 with value: 0.8324022346368715.
[I 2026-09-01 01:05:57,552] Trial 28 finished with value: 0.8100558659217877 and parameters: {'n_estimators': 462, 'max_depth': 19, 'min_samples_split': 8, 'min_samples_leaf': 6, 'max_features': None}. Best is trial 0 with value: 0.8324022346368715.
[I 2026-09-01 01:05:57,794] Trial 29 finished with value: 0.8212290502793296 and parameters: {'n_estimators': 92, 'max_depth': 15, 'min_samples_split': 11, 'min_samples_leaf': 9, 'max_features': 'log2'}. Best is trial 0 with value: 0.8324022346368715.
[I 2026-09-01 01:05:57,942] Trial 30 finished with value: 0.8324022346368715 and parameters: {'n_estimators': 50, 'max_depth': 10, 'min_samples_split': 6, 'min_samples_leaf': 6, 'max_features': 'log2'}. Best is trial 0 with value: 0.8324022346368715.
[I 2026-09-01 01:05:58,296] Trial 31 finished with value: 0.8324022346368715 and parameters: {'n_estimators': 157, 'max_depth': 21, 'min_samples_split': 8, 'min_samples_leaf': 8, 'max_features': 'sqrt'}. Best is trial 0 with value: 0.8324022346368715.
[I 2026-09-01 01:05:58,732] Trial 32 finished with value: 0.8324022346368715 and parameters: {'n_estimators': 201, 'max_depth': 21, 'min_samples_split': 4, 'min_samples_leaf': 8, 'max_features': 'sqrt'}. Best is trial 0 with value: 0.8324022346368715.
[I 2026-09-01 01:05:59,352] Trial 33 finished with value: 0.8324022346368715 and parameters: {'n_estimators': 275, 'max_depth': 16, 'min_samples_split': 7, 'min_samples_leaf': 7, 'max_features': 'sqrt'}. Best is trial 0 with value: 0.8324022346368715.
[I 2026-09-01 01:06:00,114] Trial 34 finished with value: 0.8156424581005587 and parameters: {'n_estimators': 334, 'max_depth': 23, 'min_samples_split': 10, 'min_samples_leaf': 10, 'max_features': None}. Best is trial 0 with value: 0.8324022346368715.
[I 2026-09-01 01:06:00,327] Trial 35 finished with value: 0.7988826815642458 and parameters: {'n_estimators': 80, 'max_depth': 12, 'min_samples_split': 9, 'min_samples_leaf': 5, 'max_features': 'sqrt'}. Best is trial 0 with value: 0.8324022346368715.
[I 2026-09-01 01:06:00,722] Trial 36 finished with value: 0.8100558659217877 and parameters: {'n_estimators': 161, 'max_depth': 25, 'min_samples_split': 19, 'min_samples_leaf': 9, 'max_features': None}. Best is trial 0 with value: 0.8324022346368715.
[I 2026-09-01 01:06:01,183] Trial 37 finished with value: 0.8268156424581006 and parameters: {'n_estimators': 205, 'max_depth': 29, 'min_samples_split': 16, 'min_samples_leaf': 8, 'max_features': 'sqrt'}. Best is trial 0 with value: 0.8324022346368715.
[I 2026-09-01 01:06:02,087] Trial 38 finished with value: 0.8324022346368715 and parameters: {'n_estimators': 388, 'max_depth': 18, 'min_samples_split': 3, 'min_samples_leaf': 10, 'max_features': 'log2'}. Best is trial 0 with value: 0.8324022346368715.
[I 2026-09-01 01:06:02,742] Trial 39 finished with value: 0.8044692737430168 and parameters: {'n_estimators': 273, 'max_depth': 26, 'min_samples_split': 6, 'min_samples_leaf': 4, 'max_features': 'log2'}. Best is trial 0 with value: 0.8324022346368715.
[I 2026-09-01 01:06:03,252] Trial 40 finished with value: 0.8212290502793296 and parameters: {'n_estimators': 228, 'max_depth': 28, 'min_samples_split': 18, 'min_samples_leaf': 6, 'max_features': 'sqrt'}. Best is trial 0 with value: 0.8324022346368715.
[I 2026-09-01 01:06:03,687] Trial 41 finished with value: 0.8268156424581006 and parameters: {'n_estimators': 193, 'max_depth': 30, 'min_samples_split': 19, 'min_samples_leaf': 8, 'max_features': 'sqrt'}. Best is trial 0 with value: 0.8324022346368715.
[I 2026-09-01 01:06:04,077] Trial 42 finished with value: 0.8324022346368715 and parameters: {'n_estimators': 175, 'max_depth': 29, 'min_samples_split': 17, 'min_samples_leaf': 7, 'max_features': 'sqrt'}. Best is trial 0 with value: 0.8324022346368715.
[I 2026-09-01 01:06:04,412] Trial 43 finished with value: 0.8268156424581006 and parameters: {'n_estimators': 146, 'max_depth': 26, 'min_samples_split': 20, 'min_samples_leaf': 8, 'max_features': 'sqrt'}. Best is trial 0 with value: 0.8324022346368715.
[I 2026-09-01 01:06:04,997] Trial 44 finished with value: 0.8324022346368715 and parameters: {'n_estimators': 215, 'max_depth': 29, 'min_samples_split': 19, 'min_samples_leaf': 9, 'max_features': 'sqrt'}. Best is trial 0 with value: 0.8324022346368715.
[I 2026-09-01 01:06:05,632] Trial 45 finished with value: 0.8324022346368715 and parameters: {'n_estimators': 244, 'max_depth': 24, 'min_samples_split': 13, 'min_samples_leaf': 7, 'max_features': 'sqrt'}. Best is trial 0 with value: 0.8324022346368715.
[I 2026-09-01 01:06:06,042] Trial 46 finished with value: 0.8324022346368715 and parameters: {'n_estimators': 181, 'max_depth': 27, 'min_samples_split': 16, 'min_samples_leaf': 8, 'max_features': 'log2'}. Best is trial 0 with value: 0.8324022346368715.
[I 2026-09-01 01:06:06,325] Trial 47 finished with value: 0.8268156424581006 and parameters: {'n_estimators': 119, 'max_depth': 5, 'min_samples_split': 20, 'min_samples_leaf': 9, 'max_features': 'sqrt'}. Best is trial 0 with value: 0.8324022346368715.
[I 2026-09-01 01:06:07,102] Trial 48 finished with value: 0.8156424581005587 and parameters: {'n_estimators': 306, 'max_depth': 22, 'min_samples_split': 18, 'min_samples_leaf': 10, 'max_features': None}. Best is trial 0 with value: 0.8324022346368715.
[I 2026-09-01 01:06:08,023] Trial 49 finished with value: 0.8324022346368715 and parameters: {'n_estimators': 407, 'max_depth': 25, 'min_samples_split': 11, 'min_samples_leaf': 7, 'max_features': 'sqrt'}. Best is trial 0 with value: 0.8324022346368715.
[I 2026-09-01 01:06:08,614] Trial 50 finished with value: 0.8212290502793296 and parameters: {'n_estimators': 269, 'max_depth': 29, 'min_samples_split': 12, 'min_samples_leaf': 6, 'max_features': 'log2'}. Best is trial 0 with value: 0.8324022346368715.
[I 2026-09-01 01:06:09,822] Trial 51 finished with value: 0.8324022346368715 and parameters: {'n_estimators': 500, 'max_depth': 23, 'min_samples_split': 14, 'min_samples_leaf': 9, 'max_features': 'log2'}. Best is trial 0 with value: 0.8324022346368715.
[I 2026-09-01 01:06:10,757] Trial 52 finished with value: 0.8324022346368715 and parameters: {'n_estimators': 452, 'max_depth': 28, 'min_samples_split': 7, 'min_samples_leaf': 9, 'max_features': 'log2'}. Best is trial 0 with value: 0.8324022346368715.
[I 2026-09-01 01:06:11,763] Trial 53 finished with value: 0.8324022346368715 and parameters: {'n_estimators': 487, 'max_depth': 20, 'min_samples_split': 13, 'min_samples_leaf': 10, 'max_features': 'log2'}. Best is trial 0 with value: 0.8324022346368715.
[I 2026-09-01 01:06:12,657] Trial 54 finished with value: 0.8268156424581006 and parameters: {'n_estimators': 434, 'max_depth': 25, 'min_samples_split': 15, 'min_samples_leaf': 8, 'max_features': 'log2'}. Best is trial 0 with value: 0.8324022346368715.
[I 2026-09-01 01:06:13,602] Trial 55 finished with value: 0.8324022346368715 and parameters: {'n_estimators': 465, 'max_depth': 22, 'min_samples_split': 9, 'min_samples_leaf': 10, 'max_features': 'sqrt'}. Best is trial 0 with value: 0.8324022346368715.
[I 2026-09-01 01:06:14,646] Trial 56 finished with value: 0.8324022346368715 and parameters: {'n_estimators': 482, 'max_depth': 30, 'min_samples_split': 12, 'min_samples_leaf': 9, 'max_features': 'log2'}. Best is trial 0 with value: 0.8324022346368715.
[I 2026-09-01 01:06:14,980] Trial 57 finished with value: 0.8156424581005587 and parameters: {'n_estimators': 148, 'max_depth': 26, 'min_samples_split': 20, 'min_samples_leaf': 2, 'max_features': 'sqrt'}. Best is trial 0 with value: 0.8324022346368715.
[I 2026-09-01 01:06:15,827] Trial 58 finished with value: 0.8324022346368715 and parameters: {'n_estimators': 406, 'max_depth': 18, 'min_samples_split': 16, 'min_samples_leaf': 10, 'max_features': 'sqrt'}. Best is trial 0 with value: 0.8324022346368715.
[I 2026-09-01 01:06:16,354] Trial 59 finished with value: 0.8324022346368715 and parameters: {'n_estimators': 125, 'max_depth': 27, 'min_samples_split': 6, 'min_samples_leaf': 9, 'max_features': 'log2'}. Best is trial 0 with value: 0.8324022346368715.
[I 2026-09-01 01:06:17,537] Trial 60 finished with value: 0.8100558659217877 and parameters: {'n_estimators': 370, 'max_depth': 20, 'min_samples_split': 17, 'min_samples_leaf': 8, 'max_features': None}. Best is trial 0 with value: 0.8324022346368715.
[I 2026-09-01 01:06:17,923] Trial 61 finished with value: 0.8212290502793296 and parameters: {'n_estimators': 97, 'max_depth': 27, 'min_samples_split': 8, 'min_samples_leaf': 7, 'max_features': 'sqrt'}. Best is trial 0 with value: 0.8324022346368715.
[I 2026-09-01 01:06:18,312] Trial 62 finished with value: 0.8324022346368715 and parameters: {'n_estimators': 132, 'max_depth': 28, 'min_samples_split': 10, 'min_samples_leaf': 8, 'max_features': 'sqrt'}. Best is trial 0 with value: 0.8324022346368715.
[I 2026-09-01 01:06:18,757] Trial 63 finished with value: 0.8324022346368715 and parameters: {'n_estimators': 183, 'max_depth': 30, 'min_samples_split': 7, 'min_samples_leaf': 7, 'max_features': 'sqrt'}. Best is trial 0 with value: 0.8324022346368715.
[I 2026-09-01 01:06:19,190] Trial 64 finished with value: 0.8324022346368715 and parameters: {'n_estimators': 154, 'max_depth': 22, 'min_samples_split': 9, 'min_samples_leaf': 9, 'max_features': 'sqrt'}. Best is trial 0 with value: 0.8324022346368715.
[I 2026-09-01 01:06:19,632] Trial 65 finished with value: 0.8324022346368715 and parameters: {'n_estimators': 204, 'max_depth': 29, 'min_samples_split': 8, 'min_samples_leaf': 8, 'max_features': 'sqrt'}. Best is trial 0 with value: 0.8324022346368715.
[I 2026-09-01 01:06:20,627] Trial 66 finished with value: 0.8324022346368715 and parameters: {'n_estimators': 473, 'max_depth': 24, 'min_samples_split': 5, 'min_samples_leaf': 10, 'max_features': 'sqrt'}. Best is trial 0 with value: 0.8324022346368715.
[I 2026-09-01 01:06:20,792] Trial 67 finished with value: 0.8324022346368715 and parameters: {'n_estimators': 67, 'max_depth': 27, 'min_samples_split': 11, 'min_samples_leaf': 9, 'max_features': 'sqrt'}. Best is trial 0 with value: 0.8324022346368715.
[I 2026-09-01 01:06:21,482] Trial 68 finished with value: 0.8324022346368715 and parameters: {'n_estimators': 333, 'max_depth': 29, 'min_samples_split': 14, 'min_samples_leaf': 6, 'max_features': 'log2'}. Best is trial 0 with value: 0.8324022346368715.
[I 2026-09-01 01:06:21,832] Trial 69 finished with value: 0.8268156424581006 and parameters: {'n_estimators': 166, 'max_depth': 21, 'min_samples_split': 10, 'min_samples_leaf': 7, 'max_features': 'sqrt'}. Best is trial 0 with value: 0.8324022346368715.
[I 2026-09-01 01:06:22,072] Trial 70 finished with value: 0.8100558659217877 and parameters: {'n_estimators': 108, 'max_depth': 19, 'min_samples_split': 19, 'min_samples_leaf': 8, 'max_features': None}. Best is trial 0 with value: 0.8324022346368715.
[I 2026-09-01 01:06:22,577] Trial 71 finished with value: 0.8324022346368715 and parameters: {'n_estimators': 243, 'max_depth': 16, 'min_samples_split': 20, 'min_samples_leaf': 9, 'max_features': 'sqrt'}. Best is trial 0 with value: 0.8324022346368715.
[I 2026-09-01 01:06:23,017] Trial 72 finished with value: 0.8324022346368715 and parameters: {'n_estimators': 214, 'max_depth': 20, 'min_samples_split': 19, 'min_samples_leaf': 10, 'max_features': 'sqrt'}. Best is trial 0 with value: 0.8324022346368715.
[I 2026-09-01 01:06:23,405] Trial 73 finished with value: 0.8324022346368715 and parameters: {'n_estimators': 192, 'max_depth': 26, 'min_samples_split': 17, 'min_samples_leaf': 9, 'max_features': 'sqrt'}. Best is trial 0 with value: 0.8324022346368715.
[I 2026-09-01 01:06:23,755] Trial 74 finished with value: 0.8324022346368715 and parameters: {'n_estimators': 166, 'max_depth': 30, 'min_samples_split': 18, 'min_samples_leaf': 8, 'max_features': 'sqrt'}. Best is trial 0 with value: 0.8324022346368715.
[I 2026-09-01 01:06:24,053] Trial 75 finished with value: 0.8324022346368715 and parameters: {'n_estimators': 138, 'max_depth': 17, 'min_samples_split': 6, 'min_samples_leaf': 10, 'max_features': 'sqrt'}. Best is trial 0 with value: 0.8324022346368715.
[I 2026-09-01 01:06:24,532] Trial 76 finished with value: 0.8212290502793296 and parameters: {'n_estimators': 226, 'max_depth': 19, 'min_samples_split': 8, 'min_samples_leaf': 7, 'max_features': 'sqrt'}. Best is trial 0 with value: 0.8324022346368715.
[I 2026-09-01 01:06:25,392] Trial 77 finished with value: 0.8324022346368715 and parameters: {'n_estimators': 433, 'max_depth': 24, 'min_samples_split': 20, 'min_samples_leaf': 9, 'max_features': 'log2'}. Best is trial 0 with value: 0.8324022346368715.
[I 2026-09-01 01:06:25,774] Trial 78 finished with value: 0.8324022346368715 and parameters: {'n_estimators': 174, 'max_depth': 28, 'min_samples_split': 9, 'min_samples_leaf': 8, 'max_features': 'sqrt'}. Best is trial 0 with value: 0.8324022346368715.

Best parameters:
 {'n_estimators': 480, 'max_depth': 26, 'min_samples_split': 20, 'min_samples_leaf': 8, 'max_features': 'log2'}

Best validation accuracy percentage:
 83.24022346368714 %

In [17]:
best_model = RandomForestClassifier(
    n_estimators = study.best_params["n_estimators"],
    max_depth = study.best_params["max_depth"],
    min_samples_split = study.best_params["min_samples_split"],
    min_samples_leaf = study.best_params["min_samples_leaf"],
    max_features = study.best_params["max_features"],
    random_state = 1
)

best_model.fit(X, y)

RandomForestClassifier(max_depth=26, max_features='log2', min_samples_leaf=8,
                       min_samples_split=20, n_estimators=480, random_state=1)

In [18]:
test_predictions = best_model.predict(X_test)

In [19]:
output = pd.DataFrame({
                        "PassengerId": test_data["PassengerId"], 
                        "Survived": test_predictions
                        })

output.to_csv("../output/Submissions_v3.csv", index=False)

I made use of Optuna (hyperparamter optimization framework that makes use of Bayesian style of optimization) to intelligently select ideal set of hyperparamter values after manually giving either a set of values to choose from or a range of values, within which to choose from, for each hyper parameter.

 Something i missed earlier which is a crucial step to maximise accuracy, is understanding the inter-relationships within the feature set via EDA and doing feature engineering to select the best set of features. This will be covered in the next version.